name: Java Build

on:
  push:
    branches:
      - 6.2.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Initialize git submodule
        run: git submodule init

      - name: Update git submodule
        run: git submodule update
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests -Dcheckstyle.skip

      - name: Change Dir oap-server
        run: cd oap-server

      - name: Show directory tree
        run: tree